<?php

namespace common\components;

interface AmoCrmSettings
{
    const DEFAULT_PIPELINE_ID = 9519534;
    const DEFAULT_STATUS_ID = 121212;
    const DEFAULT_LEAD_NAME = 'TEST';
    const DEFAULT_LEAD_PRICE = 0;
    const DEFAULT_NOTE_TEXT = 'No message';
    const DEFAULT_TAGS = ['Ik test' , 'ik'];


    const DEFAULT_RESPONSIBLE_USER_ID = 12406318;
    const CLIENT_ID = '207ca176-54b5-4814-85a3-e6f1c8c14dd8';
    const CLIENT_SECRET = 'IY9wC5VEv8NgJKvHdbeG07VktXQ9JpWZP7zsnPc2bOdAPL3iF3KMnVbE1L2zKFi9';
    const REDIRECT_URL = 'https://arbu-edu.uz';
    const ACCESS_TOKEN_VALUE = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImFjN2I1Y2Y2NTE4YmJmYjQyNTQ2MmI2MTkzYjBhNDNkN2Q2Y2E3NmFkOGM0YmQ2MDJjNGIzNjAxZjIxOGYzN2UxNzRkMDNlMTBiY2U2NWYwIn0.eyJhdWQiOiIyMDdjYTE3Ni01NGI1LTQ4MTQtODVhMy1lNmYxYzhjMTRkZDgiLCJqdGkiOiJhYzdiNWNmNjUxOGJiZmI0MjU0NjJiNjE5M2IwYTQzZDdkNmNhNzZhZDhjNGJkNjAyYzRiMzYwMWYyMThmMzdlMTc0ZDAzZTEwYmNlNjVmMCIsImlhdCI6MTc0NjUxMDI0MCwibmJmIjoxNzQ2NTEwMjQwLCJleHAiOjE3Njk5MDQwMDAsInN1YiI6IjEyNDA2MzE4IiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMyMzcyMTE0LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJjcm0iLCJmaWxlcyIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiLCJwdXNoX25vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiNWQ4OTdhZTctMzM3NC00MjRlLWJmOGQtNjQzNDdkNDFhZDBhIiwiYXBpX2RvbWFpbiI6ImFwaS1iLmFtb2NybS5ydSJ9.g-S_NE1oIdJxSDLOwy2uGu8t-bBUy6VFcQk5xdEvxJRyVlYluSk3QbqgoACIlCyRt_kYLIF89GLaHBcrb3PXyLCwBVKS_gz3LdNgMDvXCwELzzDrhB_j9S7uegkoIpf9PSRqxlLFStCBUtGK_CELDeZAER4THDAiBvSPRVk3COsaP5ngpdcWU_vKldJNucsHRxAO-jJwmZqWfopaLVf08NnIuYxtB6tfeVBqVDCwyrPlDbxzJ5qbxmOqJybtuA05dVt2CUwCoqBRYA3wQw6JS-rphRdaVgjFui_isyjXLljZrInhM8oVxnqZYLO5lEjvNThm1ARmmn_mZI3cNLOl_g';
    const BASE_DOMAIN = 'arbu.amocrm.ru';
}
